main/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/',views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),

]

main/catalog/urls.py
from django.urls import path, include
from . import views

app_name = 'catalog'

urlpatterns = [

    #


]

main/main/urls.py
import sys

sys.path.append('D:/Well-ecommerce-api/main/')

from basket import views
from catalog import views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from django.conf import settings
from django.conf.urls.static import static

# from main.catalog import views


router = DefaultRouter()
router.register(r'item', views.ItemView)
router.register(r'category', views.CategoryView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('', include('catalog.urls', namespace='catalog')),
    path('', views.home_page, name='home_page'),
    path('catalog/<slug:category_slug>/', views.catalog, name='category_catalog'),
    path('catalog/<slug:category_slug>/<int:item_id>/', views.item_detail, name='item_detail'),
    path('basket/', include('basket.urls', namespace='basket')),
    path('search/', views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/catalog/models.py
from django.db import models


# Create your models here.
class ItemManager(models.Manager):
    def get_queryset(self):
        return super(ItemManager, self).get_queryset().filter(is_active=True)


class Brand(models.Model):
    brand = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.brand


class Category(models.Model):
    category_name = models.CharField(max_length=100, default=None, null=True)
    category_picture = models.ImageField(upload_to='images/category-images/', default=None, null=True)
    broad_name = models.CharField(max_length=100, default=None, null=True)
    slug = models.SlugField(max_length=255, default=None, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class AdditionalPicture(models.Model):
    picture = models.ImageField(upload_to='images/additional_images/')

    class Meta:
        verbose_name = 'Дополнительное фото'
        verbose_name_plural = 'Дополнительные фото'


class Item(models.Model):
    full_name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    vendor = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    main_picture = models.ImageField(upload_to='images/')
    additional_pic = models.ManyToManyField(AdditionalPicture)
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True)
    slug = models.SlugField(max_length=255, default=None, null=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    price = models.IntegerField(default=None, null=True)
    objects = models.Manager()
    items = ItemManager()

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

    def __str__(self):
        return self.full_name

main/catalog/views.py
from django.shortcuts import render,redirect
from rest_framework import viewsets
from rest_framework.response import Response
from django.http import Http404
import sys
from .models import Item, Brand, AdditionalPicture, Category
from .serializers import ItemSerializer, CategorySerializer, BrandSerializer, AdditionalPictureSerializer

sys.path.append('D:/Well-ecommerce-api/main/')
from drf_spectacular.utils import extend_schema

from django.shortcuts import get_object_or_404


class ItemView(viewsets.ViewSet):
    # Class based viewset to all items

    queryset = Item.objects.all()

    @extend_schema(responses=ItemSerializer)
    def list(self, request):
        serializer = ItemSerializer(self.queryset, many=True)
        return Response(serializer.data)


class CategoryView(viewsets.ViewSet):
    # Class based viewset to all categories

    queryset = Category.objects.all()

    @extend_schema(responses=CategorySerializer)
    def list(self, request):
        serializer = CategorySerializer(self.queryset, many=True)
        return Response(serializer.data)


def home_page(request):
    categories = Category.objects.all()
    first_three_categories = categories[:3]
    next_three_categories = categories[3:6]
    return render(request, 'catalog/index.html',
                  {'first_three_categories': first_three_categories, 'next_three_categories': next_three_categories})


def catalog(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    items = Item.objects.filter(category_name=category)
    cart_data = request.session.get('skey', {})
    return render(request, 'catalog/catalog.html', {'category': category, 'items': items, 'cart_data': cart_data})


def item_detail(request, category_slug, item_id):
    item = get_object_or_404(Item, id=item_id)
    return render(request, 'catalog/item-of-category.html', {'category_slug': category_slug, 'item': item})



def search(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')
        item = get_object_or_404(Item, vendor=searched)
        return redirect('item_detail', category_slug=item.category_name.slug, item_id=item.id)
    else:
        raise Http404("Страница не найдена")

main/templates/catalog/catalog.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}

<head>

    <meta charset="UTF-8"/>
    <meta
            name="keywords"
            content="sawing teeth,machines,пильные зубья,гусеницы"
    />
    <meta name="author" content="Well"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/reset.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/header.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/hero.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/category.css'%}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/footer.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/category-chosen.css' %}?v=1.1"/>


    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap"
            rel="stylesheet"
    />
    {{ cart_data|json_script:"cart-data" }}
    <title>Well</title>
</head>
<body>
<!-- start header -->
{% include 'catalog/fixed/navbar.html' %}
<!-- end header -->

<!-- start main -->
<main>
    <div class="grey-stripe">
        <div class="container">
            <div class="resolution">
                <div class="nav-on-page">
                    Главная | <a class="current-link">Зубья</a>
                </div>
                <h3 class="category-item">Пильные зубья</h3>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="drop-list-brand">
            <div id="drop-trigger">
                Бренд <img src="assets\svgs\arrow-down.svg" class="down-arrow"/>
            </div>
            <div class="content">
                <div class="drop-list-brand__item">
                    <input
                            class="checkbox-custom"
                            type="checkbox"
                            id="brand1"
                            name="brand1"
                            value="brand1"
                    />
                    <label for="brand1">Bandit</label><br/>
                </div>
                <div class="drop-list-brand__item">
                    <input
                            class="checkbox-custom"
                            type="checkbox"
                            id="brand1"
                            name="brand1"
                            value="brand1"
                    />
                    <label for="brand1">Bandit</label><br/>
                </div>
                <div class="drop-list-brand__item">
                    <input
                            class="checkbox-custom"
                            type="checkbox"
                            id="brand1"
                            name="brand1"
                            value="brand1"
                    />
                    <label for="brand1">Bandit</label><br/>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <section class="items-sec">
            <ul class="category-item__list">
                <div class="container-fixed">
                    {% for item in items %}
                    <li class="category-items__item">
                        <div class="category-item-link" href="item-of-category.html">
                            <a href="{% url 'item_detail' category_slug=category.slug item_id=item.id %}">
                                <img src="{{ item.main_picture.url }}" alt="category item">
                            </a>
                            <h6 class="name-of-brand">{{item.brand}}</h6>
                            <h6 class="vendor">#Q10233T</h6>
                            <button class="{% if item.id in cart_data %}add-to-cart-btn off{% else %}add-to-cart-btn on{% endif %}"
                                    id="{{ item.id }}" data-id="{{ item.id }}">
                                {% if item.id in cart_data %}Удалить{% else %}В корзину{% endif %}
                            </button>

                        </div>
                    </li>
                    {% endfor %}
                    {{cart_data}}
                </div>
                <div class="container-fixed">

                </div>
            </ul>
        </section>
    </div>
</main>
<!-- end main -->
<!-- start  footer -->
<footer>
    <div class="container-footer">
        <div class="top-footer">
            <img src="assets\svgs\shortend.svg" alt="w-short"/>
            <p class="footer-par">Вопросы по номеру</p>
            <address class="phone">+7 (800) 5534-228</address>
            <address class="mail">pochta@mail.ru</address>
        </div>
        <div class="navigation-footer-container">
            <p class="nav-footer">Навигация по сайту</p>
            <nav class="navigation-footer">
                <ul class="nav-footer__list">
                    <li class="nav-footer__item">
                        <a href="">Категория 1</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 2</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 3</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 4</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 5</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 6</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="footer-info-container">
            <h6 class="footer-info">
                Компания «Тимбермаш Байкал» - дилер спецтехники мировых брендов
                Sany, Merko, Mesda, HBXG (Shewa), Rotobec (RTB), Hangcha, YTO,
                Orthaus, CHC Nav, FJDynamics, Gehl, Manitou, John Deere, FAE,
                Waratah, Ponsse, Gregoire Bessone, Lucas. Мы предлагаем спецтехнику
                для дорожно-строительной, лесозаготовительной, сельскохозяйственной
                отрасли, а также оригинальные запчасти и качественный сервис.
                Тимбермаш Байкал - это надежная спецтехника в наличии и под заказ;
                передовые технологии в обслуживании техники; квалифицированные
                специалисты сервиса. Приобретайте спецтехнику в лизинг на выгодных
                условиях, действует услуга Trade-IN, предлагаем варианты техники со
                стажем (б/у).
            </h6>
        </div>
        <div class="credits">
            <p class="credits_txt">
                Designed and built with all the love in the world by the
                <a class="depo" href="">depo</a> .
                <span class="license"
                >Code licensed <a class="mit" href="">MIT</a></span
                >.
            </p>
        </div>
    </div>
    <div class="bottom-footer">
        <div class="dark-stripe">
            <span class="commerce">© Well, Russia. Все права защищены.</span>
        </div>
    </div>
</footer>
</body>
<script src="\static\scripts\main.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--<script src="\static\scripts\hero.js"></script>-->
<script src="\static\scripts\index.js"></script>

<!--<script src="\static\scripts\category.js"></script>-->


<script>


</script>


<script>
$(document).ready(function() {
    // Инициализация всех кнопок


    const cartData = JSON.parse(document.getElementById('cart-data').textContent);
    console.log(cartData);


    $('button').each(function() {
        const buttonId = this.id; // Получаем id текущей кнопки

        // Проверяем значение в localStorage для каждой кнопки
        const value = localStorage.getItem(buttonId);
            if (value === '2' &&  buttonId in cartData ) {
            $(this).removeClass('on').addClass('off').text('Удалить');

        } else {
            $(this).removeClass('off').addClass('on').text('В корзину');
            localStorage.setItem(buttonId, '1');
        }
    });

    // Обработчик клика на все кнопки
    $('button').click(function(e) {
        e.preventDefault();
        var button = $(this);
        var itemId = button.data('id');

        var currentValue = parseInt(localStorage.getItem(itemId)) || 1;

        // Меняем значение на 1 или 2, в зависимости от текущего состояния
        if (currentValue === 1) {
            currentValue = 2;
            button.removeClass('on').addClass('off').text('Удалить');

        } else {
            currentValue = 1;
            button.removeClass('off').addClass('on').text('В корзину');

        }

        // Записываем новое значение в localStorage
        localStorage.setItem(itemId, currentValue);

        // Отправка AJAX запроса на добавление или удаление из корзины
        if (currentValue === 2) {
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    itemid: itemId,
                    itemqty: 1,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post',
                },
                success: function(json) {
                    document.getElementById('basket-qty').innerHTML = json.qty;
                },
                error: function(xhr, errmsg, err) {
                    // Обработка ошибок при добавлении товара в корзину
                }
            });
        } else {
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_delete" %}',
                data: {
                    itemid: itemId,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'delete',
                },
                success: function(json) {
                    document.getElementById('basket-qty').innerHTML = json.qty;
                },
                error: function(xhr, errmsg, err) {
                    // Обработка ошибок при удалении товара из корзины
                }
            });
        }
    });
});
</script>

</html>
<!-- end footer -->

main/templates/catalog/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>

    <meta charset="UTF-8"/>
    <meta
            name="keywords"
            content="sawing teeth,machines,пильные зубья,гусеницы"
    />
    <meta name="author" content="Well"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/reset.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/header.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/hero.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/category.css'%}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/footer.css' %}?v=1.1"/>


    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap"
            rel="stylesheet"
    />

    <title>Well</title>
</head>
<body>
<header>
    <nav class="navigation">
        <ul class="navigation__list">
            <li class="navigation__item">
                <a href="{% url 'home_page' %} " class="well-icon-link"
                ><img
                        src="\static\assets\svgs\header-logo.svg"
                        class="well-icon"
                        alt="logo"
                /></a>
            </li>
            <div class="icons-container">
                <form action="{% url 'search' %}" method=POST class="hidden search-form" >
                    {% csrf_token %}
                    <!-- Добавлен класс 'hidden' для скрытия формы -->
                    <input
                            class="search-input"
                            type="search"
                            name="searched"
                            placeholder="Найти по артикулу"
                    />
                    <button class="find-btn" id="new-icon" type="submit"></button>
                </form>
                <li class="navigation__item" id="search-icon">
                    <a><img src="\static\assets\svgs\search.svg" alt="search"/></a>
                    <!-- Добавлен id 'search-icon' для поиска по клику -->
                </li>
                <li class="navigation__item">
                    {% with total_qty=basket|length %}
                    <div id="basket-qty">
                        {% if total_qty > 0 %}
                           {{total_qty}}
                        {% else %}

                        {% endif %}
                        </div>
                    {% endwith %}
                    <a href="{% url 'basket:basket_summary' %}"
                    ><img src="\static\assets\svgs\cart-icon.svg" alt="cart"
                    /></a>
                </li>
            </div>
        </ul>
    </nav>
</header>
<main>
    <!-- start hero -->
    <!-- <div class="container"> -->
    <section id="hero-sec" class="hero">
        <div class="hero-pic">
            <span id="trigger-element" class="star">*</span>
            <h1 id="change-element" class="main-quote">
                make sure your business goes
                <img src="\static\assets\svgs\well-hero.svg" alt="well-hero"/>
            </h1>
            <h1 id="element-replacement" class="none not main-quote-fix">
                Убедитесь в процветании вашего бизнеса
                <!-- <div id="trigger-element" class="star">*</div> -->
            </h1>

            <h2 class="bottom-quote">
                Мы предлагаем такие-то такие-то условия и вообще у нас все круто
                прям капец клянусь.
            </h2>
            <div class="container">
                <a href="#catalog-sec" class="hero-btn">перейти к каталогу</a>
            </div>
        </div>
    </section>
    <!-- </div> -->
    <!-- end hero -->

    <!-- start catalog -->
    <section id="catalog-sec" class="catalog">
        <div class="red-stripe"></div>
        <div class="container">
            <ul class="catalog__list">

                <div class="category-container-triple">
                    {% for category in first_three_categories %}
                    <li class="catalog__item">
                        <a href="{% url 'category_catalog' category.slug %}">
                            <img
                                    src="\static\assets\pictures\item.png"
                                    alt="item-pic"
                                    class="item-pic"
                            />
                            <h4 class="category-name">{{category.category_name}}</h4>
                            <h5 class="sub-brand">
                                Bobcat
                                <div>1</div>
                            </h5>
                            <div class="dotted-line"></div>
                            <h5 class="sub-brand">
                                Delta
                                <div>4</div>
                            </h5>
                            <div class="dotted-line"></div>
                        </a>
                    </li>
                    {% endfor %}
                </div>
                <div class="category-container-triple">
                    {% for category in next_three_categories %}
                    <li class="catalog__item">
                        <a href="category.html">
                            <img
                                    src="{{ category.category_picture.url }}"
                                    alt="item-pic"
                                    class="item-pic"
                            />
                            <h4 class="category-name">{{category.category_name}}</h4>
                            <h5 class="sub-brand">
                                Bobcat
                                <div>1</div>
                            </h5>
                            <div class="dotted-line"></div>
                            <h5 class="sub-brand">
                                Delta
                                <div>4</div>
                            </h5>
                            <div class="dotted-line"></div>
                        </a>
                    </li>
                    {% endfor %}
                </div>

            </ul>
        </div>
        <div class="pinkish-stripe"></div>
    </section>
</main>

<!-- end main -->
<!-- start footer -->
<footer>
    <div class="container-footer">
        <div class="top-footer">
            <img src="\static\assets\svgs\shortend.svg" alt="w-short"/>
            <p class="footer-par">Вопросы по номеру</p>
            <address class="phone">+7 (800) 5534-228</address>
            <address class="mail">pochta@mail.ru</address>
        </div>
        <div class="navigation-footer-container">
            <p class="nav-footer">Навигация по сайту</p>
            <nav class="navigation-footer">
                <ul class="nav-footer__list">
                    <li class="nav-footer__item">
                        <a href="">Категория 1</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 2</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 3</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 4</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 5</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 6</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="footer-info-container">
            <h6 class="footer-info">
                Компания «Тимбермаш Байкал» - дилер спецтехники мировых брендов
                Sany, Merko, Mesda, HBXG (Shewa), Rotobec (RTB), Hangcha, YTO,
                Orthaus, CHC Nav, FJDynamics, Gehl, Manitou, John Deere, FAE,
                Waratah, Ponsse, Gregoire Bessone, Lucas. Мы предлагаем спецтехнику
                для дорожно-строительной, лесозаготовительной, сельскохозяйственной
                отрасли, а также оригинальные запчасти и качественный сервис.
                Тимбермаш Байкал - это надежная спецтехника в наличии и под заказ;
                передовые технологии в обслуживании техники; квалифицированные
                специалисты сервиса. Приобретайте спецтехнику в лизинг на выгодных
                условиях, действует услуга Trade-IN, предлагаем варианты техники со
                стажем (б/у).
            </h6>
        </div>
        <div class="credits">
            <p class="credits_txt">
                Designed and built with all the love in the world by the
                <a class="depo" href="">depo</a> .
                <span class="license"
                >Code licensed <a class="mit" href="">MIT</a></span
                >.
            </p>
        </div>
    </div>
    <div class="bottom-footer">
        <div class="dark-stripe">
            <span class="commerce">© Well, Russia. Все права защищены.</span>
        </div>
    </div>
</footer>
<!-- end footer -->
</body>
<script src="\static\scripts\main.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="\static\scripts\hero.js"></script>
<script src="\static\scripts\index.js"></script>

</html>