main/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/',views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),

]

main/catalog/urls.py
from django.urls import path, include
from . import views

app_name = 'catalog'

urlpatterns = [

    #


]

main/main/urls.py
import sys

sys.path.append('D:/Well-ecommerce-api/main/')

from basket import views
from catalog import views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from django.conf import settings
from django.conf.urls.static import static

# from main.catalog import views


router = DefaultRouter()
router.register(r'item', views.ItemView)
router.register(r'category', views.CategoryView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('', include('catalog.urls', namespace='catalog')),
    path('', views.home_page, name='home_page'),
    path('catalog/<slug:category_slug>/', views.catalog, name='category_catalog'),
    path('catalog/<slug:category_slug>/<int:item_id>/', views.item_detail, name='item_detail'),
    path('basket/', include('basket.urls', namespace='basket')),
    path('search/', views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/basket/models.py
from django.db import models

# Create your models here.

main/catalog/models.py
from django.db import models


# Create your models here.
class ItemManager(models.Manager):
    def get_queryset(self):
        return super(ItemManager, self).get_queryset().filter(is_active=True)


class Brand(models.Model):
    brand = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.brand


class Category(models.Model):
    category_name = models.CharField(max_length=100, default=None, null=True)
    category_picture = models.ImageField(upload_to='images/category-images/', default=None, null=True)
    broad_name = models.CharField(max_length=100, default=None, null=True)
    slug = models.SlugField(max_length=255, default=None, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class AdditionalPicture(models.Model):
    picture = models.ImageField(upload_to='images/additional_images/')

    class Meta:
        verbose_name = 'Дополнительное фото'
        verbose_name_plural = 'Дополнительные фото'


class Item(models.Model):
    full_name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    vendor = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    main_picture = models.ImageField(upload_to='images/')
    additional_pic = models.ManyToManyField(AdditionalPicture)
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True)
    slug = models.SlugField(max_length=255, default=None, null=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    price = models.IntegerField(default=None, null=True)
    objects = models.Manager()
    items = ItemManager()

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

    def __str__(self):
        return self.full_name

main/basket/views.py
from django.shortcuts import render, get_object_or_404
import sys

sys.path.append('D:/Well-ecommerce-api/main/')
from catalog.models import Item
from .basket import Basket
from django.http import JsonResponse

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.sessions.backends.db import SessionStore
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseBadRequest


# Create your views here.

def basket_summary(request):
    if request.method == 'POST':
        subtotal = int(request.POST.get('subtotal', 0))
        if subtotal <= 0:  # Проверка, что subtotal меньше или равен 0
            error_message = "Добавьте что-нибудь в корзину перед отправкой заявки."
            basket = Basket(request)
            return render(request, 'catalog/basket/summary.html', {'basket': basket, 'error_message': error_message})

        if 'fullname' in request.POST and 'email' in request.POST and 'phone' in request.POST and 'city' in request.POST:
            fullname = request.POST['fullname']
            email = request.POST['email']
            phone = request.POST['phone']
            city = request.POST['city']
            note = request.POST.get('note', '')

            basket = Basket(request)

            # Accessing session data
            session_key = request.COOKIES.get(settings.SESSION_COOKIE_NAME, None)
            session_data = {}
            if session_key:
                session = SessionStore(session_key)
                session_data = session.load()

            # Prepare message including session data
            message = f"Name: {fullname}\nEmail: {email}\nPhone: {phone}\nCity: {city}\nNote: {note}\nSubtotal: {subtotal}\nSession Data: {session_data}"

            send_mail(
                'Subject of the Email',
                message,
                settings.EMAIL_HOST_USER,  # From email address
                [settings.EMAIL_HOST_USER],  # To email address
                fail_silently=False,
            )

            # Clear session data
            if session_key:
                session.delete()

            return HttpResponseRedirect(reverse('basket:basket_summary'))  # Redirect after form submission

    basket = Basket(request)

    return render(request, 'catalog/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        item_id = int(request.POST.get('itemid'))
        item_qty = int(request.POST.get('itemqty'))
        item = get_object_or_404(Item, id=item_id)

        basket.add(item, qty=item_qty)
        basketqty = basket.__len__()

        response = JsonResponse({
            'qty': basketqty
        })

        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'delete':
        item_id = int(request.POST.get('itemid'))
        basket.delete(item=item_id)
        baskettotal = basket.get_total_price()
        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})

        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'update':
        item_id = int(request.POST.get('itemid'))
        item_qty = int(request.POST.get('itemqty'))
        basket.update(item=item_id, qty=item_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

main/catalog/views.py
from django.shortcuts import render,redirect
from rest_framework import viewsets
from rest_framework.response import Response
from django.http import Http404
import sys
from .models import Item, Brand, AdditionalPicture, Category
from .serializers import ItemSerializer, CategorySerializer, BrandSerializer, AdditionalPictureSerializer

sys.path.append('D:/Well-ecommerce-api/main/')
from drf_spectacular.utils import extend_schema

from django.shortcuts import get_object_or_404


class ItemView(viewsets.ViewSet):
    # Class based viewset to all items

    queryset = Item.objects.all()

    @extend_schema(responses=ItemSerializer)
    def list(self, request):
        serializer = ItemSerializer(self.queryset, many=True)
        return Response(serializer.data)


class CategoryView(viewsets.ViewSet):
    # Class based viewset to all categories

    queryset = Category.objects.all()

    @extend_schema(responses=CategorySerializer)
    def list(self, request):
        serializer = CategorySerializer(self.queryset, many=True)
        return Response(serializer.data)


def home_page(request):
    categories = Category.objects.all()
    first_three_categories = categories[:3]
    next_three_categories = categories[3:6]
    return render(request, 'catalog/index.html',
                  {'first_three_categories': first_three_categories, 'next_three_categories': next_three_categories})


def catalog(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    items = Item.objects.filter(category_name=category)
    cart_data = request.session.get('skey', {})
    return render(request, 'catalog/catalog.html', {'category': category, 'items': items, 'cart_data': cart_data})


def item_detail(request, category_slug, item_id):
    item = get_object_or_404(Item, id=item_id)
    return render(request, 'catalog/item-of-category.html', {'category_slug': category_slug, 'item': item})



def search(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')
        item = get_object_or_404(Item, vendor=searched)
        return redirect('item_detail', category_slug=item.category_name.slug, item_id=item.id)
    else:
        raise Http404("Страница не найдена")

main/templates/catalog/basket/summary.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8"/>
    <meta
            name="keywords"
            content="sawing teeth,machines,пильные зубья,гусеницы"
    />
    <meta name="author" content="Well"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/reset.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/hero.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/category.css'%}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/footer.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/cart.css' %}?v=1.1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/header.css' %}?v=1.1"/>

    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap"
            rel="stylesheet"
    />
    <title>Item of category</title>
</head>
<body>

{% include 'catalog/fixed/navbar.html' %}

<main>
    <div class="grey-stripe">
        <div class="container">
            <div class="resolution">
                <div class="nav-on-page">
                    Главная |
                    <a class="current-link">Корзина</a>
                </div>
                <h3 class="category-item">Корзина</h3>
            </div>
        </div>
    </div>
    <div class="container">
        <section class="cart">
            <div class="cart__container">
                <ul class="cart__list">
                    {% for thing in basket %}
                    {% with item=thing.item %}
                    <li class="cart__item" data-price="{{item.price}}">
                        <button class="cross" id="delete-btn" data-id="{{item.id}}"></button>


                        <div class="test" href="">
                            <div class="cart-pic-cont">
                                <img
                                        class="cart-pic"
                                        src="{{item.main_picture.url}}"
                                        alt="cart-item"
                                />
                            </div>
                            <div>
                                <p class="price" id="price-item" data-item="{{item.id}}">{{thing.total_price}}₽</p>
                                <h6 class="name-of-item-cart">
                                    {{item.full_name}}
                                </h6>
                                <span class="qnty"
                                >Кол-во:
                      <input class="amount" type="number" value="{{thing.qty}}" id="select{{item.id}}" name="quantity"
                             min="1" max="200"></span>

                                <button id="update-btn" class="update" data-index="{{item.id}}">update</button>
                            </div>
                        </div>
                        <h6 class="name-of-brand-cart">Bandit</h6>
                        <h6 class="vendor-cart">#Q10233T</h6>
                    </li>
                    {% endwith %}
                    {% endfor %}
                </ul>
            </div>
            <form class="cart-form" method="POST" action="{% url 'basket:basket_summary' %}">
                {%csrf_token%}
                <div>
                    <div class="total">
                        Итог*
                        <div id="subtotall">{{basket.get_total_price}}₽</div>
                        <input type="hidden" id="subtotal" name="subtotal" value="{{basket.get_total_price}}">
                    </div>
                </div>
                {% if error_message %}
                <p class="error">{{ error_message }}</p>
                {% endif %}
                <div class="underscore"></div>
                <div class="total-line"></div>
                <div>
                    <label for="fullname"></label>
                    <input
                            class="input"
                            placeholder="ФИО"
                            type="text"
                            id="fullname"
                            name="fullname"
                            required
                    />
                </div>
                <div>
                    <label for="email"></label>
                    <input
                            placeholder="Email"
                            type="email"
                            id="email"
                            name="email"
                            required
                    />
                </div>
                <div>
                    <label for="phone"></label>
                    <input
                            placeholder="Телефон"
                            type="tel"
                            id="phone"
                            name="phone"
                            required
                    />
                </div>
                <div>
                    <label for="city"></label>
                    <input placeholder="Город" type="text" id="city" name="city"/>
                </div>
                <div>
                    <label for="note"></label>
                    <textarea
                            class="note"
                            placeholder="Примечание (при необходимости)"
                            id="note"
                            name="note"
                    ></textarea>
                </div>
                <div class="btn-cont">
                    <button class="sub-btn" type="submit">Отправить заявку</button>
                </div>
            </form>
        </section>
    </div>
</main>
<footer class="">
    <div class="container-footer">
        <div class="top-footer">
            <img src="assets\svgs\shortend.svg" alt="w-short"/>
            <p class="footer-par">Вопросы по номеру</p>
            <address class="phone">+7 (800) 5534-228</address>
            <address class="mail">pochta@mail.ru</address>
        </div>
        <div class="navigation-footer-container">
            <p class="nav-footer">Навигация по сайту</p>
            <nav class="navigation-footer">
                <ul class="nav-footer__list">
                    <li class="nav-footer__item">
                        <a href="">Категория 1</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 2</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 3</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 4</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 5</a>
                    </li>
                    <li class="nav-footer__item">
                        <a href="">Категория 6</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="footer-info-container">
            <h6 class="footer-info">
                Компания «Тимбермаш Байкал» - дилер спецтехники мировых брендов
                Sany, Merko, Mesda, HBXG (Shewa), Rotobec (RTB), Hangcha, YTO,
                Orthaus, CHC Nav, FJDynamics, Gehl, Manitou, John Deere, FAE,
                Waratah, Ponsse, Gregoire Bessone, Lucas. Мы предлагаем спецтехнику
                для дорожно-строительной, лесозаготовительной, сельскохозяйственной
                отрасли, а также оригинальные запчасти и качественный сервис.
                Тимбермаш Байкал - это надежная спецтехника в наличии и под заказ;
                передовые технологии в обслуживании техники; квалифицированные
                специалисты сервиса. Приобретайте спецтехнику в лизинг на выгодных
                условиях, действует услуга Trade-IN, предлагаем варианты техники со
                стажем (б/у).
            </h6>
        </div>
        <div class="credits">
            <p class="credits_txt">
                Designed and built with all the love in the world by the
                <a class="depo" href="">depo</a> .
                <span class="license"
                >Code licensed <a class="mit" href="">MIT</a></span
                >.
            </p>
        </div>
    </div>
    <div class="bottom-footer">
        <div class="dark-stripe">
            <span class="commerce">© Well, Russia. Все права защищены.</span>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="\static\scripts\index.js"></script>
<script src="\static\scripts\cart.js"></script>

<script>
          $(document).on('click','.cross',function(e) {
              e.preventDefault();

              $.ajax({
                  type: 'POST',
                  url: '{% url "basket:basket_delete" %}',
                  data: {
                      itemid : $(this).data('id'),
                      csrfmiddlewaretoken : '{{csrf_token}}',
                      action: 'delete',
                  },
                  success: function(json){
                      document.getElementById('basket-qty').innerHTML = json.qty
                      document.getElementById('subtotall').innerHTML = json.subtotal + '₽'
                  },
                  error: function(xhr,errmsg,err){}
               });

          })



<!-- update  Item  -->
    $(document).on('click', '.update', function(e) {
        e.preventDefault();
        var button = $(this);
        var itemid = button.data('index');
        var quantityInput = $('#select' + itemid);
        var newQuantity = quantityInput.val();

        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_update" %}',
            data: {
                itemid: itemid,
                itemqty: newQuantity,
                csrfmiddlewaretoken: '{{csrf_token}}',
                action: 'update',
            },
            success: function(json) {
                var itemTotalPrice = newQuantity * button.closest('.cart__item').data('price');
                button.closest('.cart__item').find('.price').text(itemTotalPrice + '₽');
                document.getElementById('basket-qty').innerHTML = json.qty
                document.getElementById('subtotall').innerHTML = json.subtotal + '₽'
            },
            error: function(xhr, errmsg, err) {

            }
        });
    });

</script>
<script>
    let formSubmitted = false;
    const form = document.querySelector('.cart-form');

    form.addEventListener('submit', function(event) {
        if (formSubmitted) {
            event.preventDefault(); // Предотвращаем отправку формы, если уже была отправка
        } else {
            formSubmitted = true;
            setTimeout(() => {
                formSubmitted = false;
            }, 3000); // 3000 миллисекунд = 3 секунды
        }
    });
</script>


<!-- end main -->
</body>
</html>